/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/stock/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock Metrics */
        get: operations["get_stock_metrics_api_stock__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock History */
        get: operations["get_stock_history_api_stock__ticker__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock Indicators */
        get: operations["get_stock_indicators_api_stock__ticker__indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Summary
         * @description Returns all macro data (liquidity, debt status, real rates, CPI) in a single request.
         *
         *     This endpoint is optimized for frontend dashboards that need multiple macro indicators.
         *     Instead of making 4 separate API calls, the frontend can fetch everything at once,
         *     reducing latency and preventing redundant database queries.
         *
         *     The response includes a summary object with the latest values for quick display.
         */
        get: operations["get_macro_summary_api_macro_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/liquidity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Liquidity
         * @description Returns historical M2 Money Supply and YoY % growth with metadata.
         *     Frontend should poll this endpoint periodically and check metadata.is_stale.
         */
        get: operations["get_macro_liquidity_api_macro_liquidity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/debt-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Debt Status
         * @description Returns the Interest-to-Tax ratio and individual components with metadata.
         *     Frontend should poll this endpoint periodically and check metadata.is_stale.
         */
        get: operations["get_macro_debt_status_api_macro_debt_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/real-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Real Rates
         * @description Returns (10-Year Treasury Yield - CPI Inflation Rate) with metadata.
         *     Frontend should poll this endpoint periodically and check metadata.is_stale.
         */
        get: operations["get_macro_real_rates_api_macro_real_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/cpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Cpi
         * @description Returns historical CPI data with metadata.
         *     Frontend should poll this endpoint periodically and check metadata.is_stale.
         */
        get: operations["get_macro_cpi_api_macro_cpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sentiment/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sentiment
         * @description Get news sentiment analysis for a stock ticker.
         *     Returns sentiment score, label, and recent headlines with individual scores.
         */
        get: operations["get_sentiment_api_sentiment__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comparison/barbell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Barbell Comparison Endpoint
         * @description Fetch normalized comparison data for Barbell Strategy (Hard vs Soft Assets).
         */
        get: operations["barbell_comparison_endpoint_api_comparison_barbell_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Risk Data
         * @description Get full risk data including logarithmic regression bands for an asset.
         *
         *     Returns risk score (0.0-1.0), fair value bands, and current price position.
         *     Best used for charting with band overlays.
         *
         *     Supported tickers: BTC, ETH (and their -USD variants)
         */
        get: operations["get_risk_data_api_v1_risk__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/{ticker}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Risk Score
         * @description Get lightweight risk score data for an asset (faster, for dashboard cards).
         *
         *     Returns just the risk score, current band, price, and fair value.
         */
        get: operations["get_risk_score_api_v1_risk__ticker__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crypto/dominance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crypto Dominance
         * @description Returns global cryptocurrency market dominance data.
         *
         *     Includes:
         *     - Total market cap
         *     - Bitcoin (BTC) dominance percentage
         *     - Ethereum (ETH) dominance percentage
         *     - Altcoin market cap (Total - BTC - ETH)
         *
         *     Data is fetched from Redis cache (fast) or PostgreSQL (fallback).
         *     Background worker updates this daily to avoid rate limits.
         *
         *     Args:
         *         days: Number of days of historical data (max 365 for demo API key)
         *
         *     Returns:
         *         {
         *             'data': List of data points with timestamp, total_mcap, btc_dominance, etc.
         *             'metadata': {'last_updated': ISO timestamp, 'is_stale': bool}
         *         }
         */
        get: operations["get_crypto_dominance_api_crypto_dominance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CPIPoint */
        CPIPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /**
         * CPIResponse
         * @description Response with data and metadata for CPI endpoint.
         */
        CPIResponse: {
            /** Data */
            data: components["schemas"]["CPIPoint"][];
            metadata: components["schemas"]["MacroDataMetadata"];
        };
        /** ComparisonResult */
        ComparisonResult: {
            /** Date */
            date: string;
            /** Hard Index */
            Hard_Index: number;
            /** Soft Index */
            Soft_Index: number;
            /** Ratio */
            Ratio: number;
            /** Ratio Normalized */
            Ratio_Normalized: number;
        };
        /** CurrentBand */
        CurrentBand: {
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** DebtPoint */
        DebtPoint: {
            /** Date */
            date: string;
            /** Interest Payments */
            interest_payments: number;
            /** Tax Receipts */
            tax_receipts: number;
            /** Ratio */
            ratio: number;
        };
        /**
         * DebtStatusResponse
         * @description Response with data and metadata for debt status endpoint.
         */
        DebtStatusResponse: {
            /** Data */
            data: components["schemas"]["DebtPoint"][];
            metadata: components["schemas"]["MacroDataMetadata"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiquidityPoint */
        LiquidityPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
            /** Growth Rate */
            growth_rate?: number | null;
        };
        /**
         * LiquidityResponse
         * @description Response with data and metadata for liquidity endpoint.
         */
        LiquidityResponse: {
            /** Data */
            data: components["schemas"]["LiquidityPoint"][];
            metadata: components["schemas"]["MacroDataMetadata"];
        };
        /**
         * MacroDataMetadata
         * @description Metadata about macro data freshness.
         */
        MacroDataMetadata: {
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
        };
        /**
         * MacroMetrics
         * @description Summary snapshot of macro metrics.
         */
        MacroMetrics: {
            /** M2 Supply */
            m2_supply: number;
            /** M2 Growth */
            m2_growth: number;
            /** Debt To Tax Ratio */
            debt_to_tax_ratio: number;
            /** Real Rate */
            real_rate: number;
        };
        /**
         * MacroSummaryResponse
         * @description Aggregated macro data response for efficient frontend fetching.
         *     Returns all macro indicators in a single request to prevent
         *     redundant API calls from multiple dashboard components.
         */
        MacroSummaryResponse: {
            liquidity: components["schemas"]["LiquidityResponse"];
            debt_status: components["schemas"]["DebtStatusResponse"];
            real_rates: components["schemas"]["RealRatesResponse"];
            cpi: components["schemas"]["CPIResponse"];
            summary: components["schemas"]["MacroMetrics"];
        };
        /** RealRatePoint */
        RealRatePoint: {
            /** Date */
            date: string;
            /** Treasury Yield 10Y */
            treasury_yield_10y: number;
            /** Cpi Inflation */
            cpi_inflation: number;
            /** Real Rate */
            real_rate: number;
        };
        /**
         * RealRatesResponse
         * @description Response with data and metadata for real rates endpoint.
         */
        RealRatesResponse: {
            /** Data */
            data: components["schemas"]["RealRatePoint"][];
            metadata: components["schemas"]["MacroDataMetadata"];
        };
        /** RegressionParams */
        RegressionParams: {
            /** A */
            a: number;
            /** B */
            b: number;
            /** Std */
            std: number;
        };
        /** RiskBand */
        RiskBand: {
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Std Multiplier */
            std_multiplier: number;
            /** Values */
            values: components["schemas"]["RiskBandValue"][];
        };
        /** RiskBandValue */
        RiskBandValue: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /**
         * RiskResponse
         * @description Full risk data response with bands for charting.
         */
        RiskResponse: {
            /** Ticker */
            ticker: string;
            /** Current Risk */
            current_risk: number;
            current_band: components["schemas"]["CurrentBand"];
            /** Current Price */
            current_price: number;
            /** Fair Value */
            fair_value: number;
            /** Bands */
            bands: components["schemas"]["RiskBand"][];
            regression_params: components["schemas"]["RegressionParams"];
            /** Inception Date */
            inception_date: string;
            /** Data Points */
            data_points: number;
        };
        /**
         * RiskScoreResponse
         * @description Lightweight risk score response for dashboard cards.
         */
        RiskScoreResponse: {
            /** Ticker */
            ticker: string;
            /** Current Risk */
            current_risk: number;
            current_band: components["schemas"]["CurrentBand"];
            /** Current Price */
            current_price: number;
            /** Fair Value */
            fair_value: number;
        };
        /** SentimentArticle */
        SentimentArticle: {
            /** Title */
            title: string;
            /** Link */
            link: string;
            /** Publisher */
            publisher: string;
            /** Score */
            score: number;
        };
        /** SentimentResponse */
        SentimentResponse: {
            /** Sentiment Score */
            sentiment_score: number;
            /** Sentiment Label */
            sentiment_label: string;
            /** News Count */
            news_count: number;
            /** Headlines */
            headlines: components["schemas"]["SentimentArticle"][];
            /** Message */
            message?: string | null;
        };
        /** StockHistoryPoint */
        StockHistoryPoint: {
            /** Datetime */
            Datetime: string;
            /** Open */
            Open: number;
            /** High */
            High: number;
            /** Low */
            Low: number;
            /** Close */
            Close: number;
            /** Volume */
            Volume: number;
        };
        /** StockIndicatorsPoint */
        StockIndicatorsPoint: {
            /** Datetime */
            Datetime: string;
            /** Sma 20 */
            SMA_20?: number | null;
            /** Ema 20 */
            EMA_20?: number | null;
            /** Ema 21 */
            EMA_21?: number | null;
            /** Rsi 14 */
            RSI_14?: number | null;
        };
        /** StockMetrics */
        StockMetrics: {
            /** Last Close */
            last_close: number;
            /** Change */
            change: number;
            /** Pct Change */
            pct_change: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Volume */
            volume: number;
            /** Volatility */
            volatility?: number | null;
            /** Sharpe Ratio */
            sharpe_ratio?: number | null;
            /** Risk Free Rate */
            risk_free_rate: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_stock_metrics_api_stock__ticker__get: {
        parameters: {
            query?: {
                /** @description Time period (e.g., 1d, 5d, 1mo) */
                period?: string;
                /** @description Data interval (e.g., 1m, 5m, 1h) */
                interval?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMetrics"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_stock_history_api_stock__ticker__history_get: {
        parameters: {
            query?: {
                period?: string;
                interval?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockHistoryPoint"][];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_stock_indicators_api_stock__ticker__indicators_get: {
        parameters: {
            query?: {
                period?: string;
                interval?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockIndicatorsPoint"][];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_summary_api_macro_summary_get: {
        parameters: {
            query?: {
                /** @description Number of days of history to return */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroSummaryResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_liquidity_api_macro_liquidity_get: {
        parameters: {
            query?: {
                /** @description Number of days of history to return */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiquidityResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_debt_status_api_macro_debt_status_get: {
        parameters: {
            query?: {
                /** @description Number of days of history to return */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtStatusResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_real_rates_api_macro_real_rates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealRatesResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_cpi_api_macro_cpi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CPIResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sentiment_api_sentiment__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentimentResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    barbell_comparison_endpoint_api_comparison_barbell_get: {
        parameters: {
            query?: {
                /** @description Time period (e.g. 1y, ytd) */
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResult"][];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_risk_data_api_v1_risk__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_risk_score_api_v1_risk__ticker__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskScoreResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_crypto_dominance_api_crypto_dominance_get: {
        parameters: {
            query?: {
                /** @description Number of days of history to return (max 365 for demo key) */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
