/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/stock/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock Metrics */
        get: operations["get_stock_metrics_api_stock__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock History */
        get: operations["get_stock_history_api_stock__ticker__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock Indicators */
        get: operations["get_stock_indicators_api_stock__ticker__indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/fundamentals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Fundamentals
         * @description Fetch fundamental metrics for a stock.
         *
         *     Returns valuation metrics (P/E, P/S), risk metrics (Beta, 52-week range),
         *     and profitability metrics (EPS, Profit Margin, Dividend Yield).
         */
        get: operations["get_stock_fundamentals_api_stock__ticker__fundamentals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Summary
         * @description Returns all macro data (liquidity, debt status, real rates, CPI) in a single request.
         *
         *     This endpoint is optimized for frontend dashboards that need multiple macro indicators.
         *     Instead of making 4 separate API calls, the frontend can fetch everything at once,
         *     reducing latency and preventing redundant database queries.
         *
         *     The response includes a summary object with the latest values for quick display.
         */
        get: operations["get_macro_summary_api_macro_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/liquidity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Liquidity
         * @description Returns historical M2 Money Supply and YoY % growth with metadata.
         *     Frontend should poll this endpoint periodically and check metadata.is_stale.
         */
        get: operations["get_macro_liquidity_api_macro_liquidity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/debt-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Debt Status
         * @description Returns the Interest-to-Tax ratio and individual components with metadata.
         *     Frontend should poll this endpoint periodically and check metadata.is_stale.
         */
        get: operations["get_macro_debt_status_api_macro_debt_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/real-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Real Rates
         * @description Returns (10-Year Treasury Yield - CPI Inflation Rate) with metadata.
         *     Frontend should poll this endpoint periodically and check metadata.is_stale.
         */
        get: operations["get_macro_real_rates_api_macro_real_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/cpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Cpi
         * @description Returns historical CPI data with metadata.
         *     Frontend should poll this endpoint periodically and check metadata.is_stale.
         */
        get: operations["get_macro_cpi_api_macro_cpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Macro Series
         * @description Returns one or more macro series for chart overlay.
         *
         *     This endpoint is optimized for the Ticker Analysis page to overlay macro indicators
         *     (like M2 Money Supply, CPI) on stock price charts. The data is resampled to daily
         *     frequency by default to align with stock data granularity.
         *
         *     Example: `/api/macro/series?series_ids=M2SL,CPIAUCSL&days=365`
         */
        get: operations["get_macro_series_api_macro_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/overlays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Overlays
         * @description Returns list of available macro series for overlay selection in the UI.
         *
         *     This endpoint provides metadata about each overlay-friendly series,
         *     including name, description, frequency, and units.
         */
        get: operations["get_available_overlays_api_macro_overlays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sentiment/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sentiment
         * @description Get news sentiment analysis for a stock ticker.
         *     Returns sentiment score, label, and recent headlines with individual scores.
         */
        get: operations["get_sentiment_api_sentiment__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comparison/barbell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Barbell Comparison Endpoint
         * @description Fetch normalized comparison data for Barbell Strategy (Hard vs Soft Assets).
         */
        get: operations["barbell_comparison_endpoint_api_comparison_barbell_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Risk Data
         * @description Get full risk data including logarithmic regression bands for an asset.
         *
         *     Returns risk score (0.0-1.0), fair value bands, and current price position.
         *     Best used for charting with band overlays.
         *
         *     Supported tickers: BTC, ETH (and their -USD variants)
         */
        get: operations["get_risk_data_api_v1_risk__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/{ticker}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Risk Score
         * @description Get lightweight risk score data for an asset (faster, for dashboard cards).
         *
         *     Returns just the risk score, current band, price, and fair value.
         */
        get: operations["get_risk_score_api_v1_risk__ticker__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crypto/dominance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crypto Dominance
         * @description Returns global cryptocurrency market dominance data.
         *
         *     Includes:
         *     - Total market cap
         *     - Bitcoin (BTC) dominance percentage
         *     - Ethereum (ETH) dominance percentage
         *     - Altcoin market cap (Total - BTC - ETH)
         *
         *     Data is fetched from Redis cache (fast) or PostgreSQL (fallback).
         *     Background worker updates this daily to avoid rate limits.
         *
         *     Args:
         *         days: Number of days of historical data (max 365 for demo API key)
         *
         *     Returns:
         *         {
         *             'data': List of data points with timestamp, total_mcap, btc_dominance, etc.
         *             'metadata': {'last_updated': ISO timestamp, 'is_stale': bool}
         *         }
         */
        get: operations["get_crypto_dominance_api_crypto_dominance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get App Config
         * @description Returns application configuration.
         *
         *     This endpoint exposes non-sensitive configuration values that the frontend
         *     needs to stay in sync with the backend. Changes to these values in config.py
         *     are automatically reflected here.
         *
         *     Use cases:
         *     - Timeframe options for chart controls
         *     - Cache TTL for data freshness indicators
         *     - API rate limits for client-side throttling
         *     - Chart indicator defaults
         *     - Market indices and watchlist tickers
         *
         *     Note: Sensitive values (API keys, database URLs) are NOT exposed.
         */
        get: operations["get_app_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Basic health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detailed Health Check
         * @description Detailed health check with database, Redis, and table validation.
         *
         *     Returns status of all critical services.
         */
        get: operations["detailed_health_check_health_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiLimitsConfig
         * @description API rate limit information.
         */
        ApiLimitsConfig: {
            /** Fred Daily Limit */
            fred_daily_limit: number;
            /** Coingecko Per Minute */
            coingecko_per_minute: number;
        };
        /**
         * AppConfigResponse
         * @description Application configuration response.
         *
         *     Exposes non-sensitive configuration to frontend for synchronization.
         *     This ensures frontend and backend use consistent settings.
         */
        AppConfigResponse: {
            /** Version */
            version: string;
            /** Timeframes */
            timeframes: components["schemas"]["TimeframeConfig"][];
            cache: components["schemas"]["CacheConfig"];
            api_limits: components["schemas"]["ApiLimitsConfig"];
            chart_defaults: components["schemas"]["ChartDefaultsConfig"];
            /** Market Indices */
            market_indices: {
                [key: string]: unknown;
            }[];
            /** Watchlist Tickers */
            watchlist_tickers: string[];
        };
        /**
         * AvailableOverlaysResponse
         * @description List of available macro series for overlay selection.
         */
        AvailableOverlaysResponse: {
            /** Overlays */
            overlays: components["schemas"]["MacroSeriesInfo"][];
        };
        /** CPIPoint */
        CPIPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /**
         * CPIResponse
         * @description Response with data and metadata for CPI endpoint.
         */
        CPIResponse: {
            /** Data */
            data: components["schemas"]["CPIPoint"][];
            metadata: components["schemas"]["MacroDataMetadata"];
        };
        /**
         * CacheConfig
         * @description Cache TTL and staleness configuration.
         */
        CacheConfig: {
            /** Ttl Seconds */
            ttl_seconds: number;
            /** Stale Threshold Hours */
            stale_threshold_hours: number;
        };
        /**
         * ChartDefaultsConfig
         * @description Default chart settings.
         */
        ChartDefaultsConfig: {
            /** Sma Window */
            sma_window: number;
            /** Ema Window */
            ema_window: number;
            /** Rsi Window */
            rsi_window: number;
            /** Default Ticker */
            default_ticker: string;
            /** Default Tickers */
            default_tickers: string[];
        };
        /** ComparisonResult */
        ComparisonResult: {
            /** Date */
            date: string;
            /** Hard Index */
            Hard_Index: number;
            /** Soft Index */
            Soft_Index: number;
            /** Ratio */
            Ratio: number;
            /** Ratio Normalized */
            Ratio_Normalized: number;
        };
        /** CurrentBand */
        CurrentBand: {
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** DebtPoint */
        DebtPoint: {
            /** Date */
            date: string;
            /** Interest Payments */
            interest_payments: number;
            /** Tax Receipts */
            tax_receipts: number;
            /** Ratio */
            ratio: number;
        };
        /**
         * DebtStatusResponse
         * @description Response with data and metadata for debt status endpoint.
         */
        DebtStatusResponse: {
            /** Data */
            data: components["schemas"]["DebtPoint"][];
            metadata: components["schemas"]["MacroDataMetadata"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiquidityPoint */
        LiquidityPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
            /** Growth Rate */
            growth_rate?: number | null;
        };
        /**
         * LiquidityResponse
         * @description Response with data and metadata for liquidity endpoint.
         */
        LiquidityResponse: {
            /** Data */
            data: components["schemas"]["LiquidityPoint"][];
            metadata: components["schemas"]["MacroDataMetadata"];
        };
        /**
         * MacroDataMetadata
         * @description Metadata about macro data freshness.
         */
        MacroDataMetadata: {
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
        };
        /**
         * MacroMetrics
         * @description Summary snapshot of macro metrics.
         */
        MacroMetrics: {
            /** M2 Supply */
            m2_supply: number;
            /** M2 Growth */
            m2_growth: number;
            /** Debt To Tax Ratio */
            debt_to_tax_ratio: number;
            /** Real Rate */
            real_rate: number;
        };
        /**
         * MacroSeriesData
         * @description Response for a single macro series with data and metadata.
         */
        MacroSeriesData: {
            /** Series Id */
            series_id: string;
            /** Name */
            name: string;
            /** Data */
            data: components["schemas"]["MacroSeriesPoint"][];
            metadata: components["schemas"]["MacroDataMetadata"];
        };
        /**
         * MacroSeriesInfo
         * @description Metadata about a single macro series.
         */
        MacroSeriesInfo: {
            /** Series Id */
            series_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Frequency */
            frequency: string;
            /** Units */
            units?: string | null;
        };
        /**
         * MacroSeriesPoint
         * @description Single data point for a macro time series overlay.
         */
        MacroSeriesPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /**
         * MacroSeriesResponse
         * @description Response for macro series endpoint.
         *     Supports single or batch series requests for chart overlays.
         */
        MacroSeriesResponse: {
            /** Series */
            series: components["schemas"]["MacroSeriesData"][];
        };
        /**
         * MacroSummaryResponse
         * @description Aggregated macro data response for efficient frontend fetching.
         *     Returns all macro indicators in a single request to prevent
         *     redundant API calls from multiple dashboard components.
         */
        MacroSummaryResponse: {
            liquidity: components["schemas"]["LiquidityResponse"];
            debt_status: components["schemas"]["DebtStatusResponse"];
            real_rates: components["schemas"]["RealRatesResponse"];
            cpi: components["schemas"]["CPIResponse"];
            summary: components["schemas"]["MacroMetrics"];
        };
        /** RealRatePoint */
        RealRatePoint: {
            /** Date */
            date: string;
            /** Treasury Yield 10Y */
            treasury_yield_10y: number;
            /** Cpi Inflation */
            cpi_inflation: number;
            /** Real Rate */
            real_rate: number;
        };
        /**
         * RealRatesResponse
         * @description Response with data and metadata for real rates endpoint.
         */
        RealRatesResponse: {
            /** Data */
            data: components["schemas"]["RealRatePoint"][];
            metadata: components["schemas"]["MacroDataMetadata"];
        };
        /** RegressionParams */
        RegressionParams: {
            /** A */
            a: number;
            /** B */
            b: number;
            /** Std */
            std: number;
        };
        /** RiskBand */
        RiskBand: {
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Std Multiplier */
            std_multiplier: number;
            /** Values */
            values: components["schemas"]["RiskBandValue"][];
        };
        /** RiskBandValue */
        RiskBandValue: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /**
         * RiskResponse
         * @description Full risk data response with bands for charting.
         */
        RiskResponse: {
            /** Ticker */
            ticker: string;
            /** Current Risk */
            current_risk: number;
            current_band: components["schemas"]["CurrentBand"];
            /** Current Price */
            current_price: number;
            /** Fair Value */
            fair_value: number;
            /** Bands */
            bands: components["schemas"]["RiskBand"][];
            regression_params: components["schemas"]["RegressionParams"];
            /** Inception Date */
            inception_date: string;
            /** Data Points */
            data_points: number;
        };
        /**
         * RiskScoreResponse
         * @description Lightweight risk score response for dashboard cards.
         */
        RiskScoreResponse: {
            /** Ticker */
            ticker: string;
            /** Current Risk */
            current_risk: number;
            current_band: components["schemas"]["CurrentBand"];
            /** Current Price */
            current_price: number;
            /** Fair Value */
            fair_value: number;
        };
        /** SentimentArticle */
        SentimentArticle: {
            /** Title */
            title: string;
            /** Link */
            link: string;
            /** Publisher */
            publisher: string;
            /** Score */
            score: number;
        };
        /** SentimentResponse */
        SentimentResponse: {
            /** Sentiment Score */
            sentiment_score: number;
            /** Sentiment Label */
            sentiment_label: string;
            /** News Count */
            news_count: number;
            /** Headlines */
            headlines: components["schemas"]["SentimentArticle"][];
            /** Message */
            message?: string | null;
        };
        /**
         * StockFundamentals
         * @description Fundamental metrics for stock valuation and risk analysis.
         */
        StockFundamentals: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Market Cap */
            market_cap?: number | null;
            /** Trailing Pe */
            trailing_pe?: number | null;
            /** Forward Pe */
            forward_pe?: number | null;
            /** Beta */
            beta?: number | null;
            /** Fifty Two Week High */
            fifty_two_week_high?: number | null;
            /** Fifty Two Week Low */
            fifty_two_week_low?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Trailing Eps */
            trailing_eps?: number | null;
            /** Profit Margin */
            profit_margin?: number | null;
            /** Price To Sales */
            price_to_sales?: number | null;
            /** Debt To Equity */
            debt_to_equity?: number | null;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
        };
        /** StockHistoryPoint */
        StockHistoryPoint: {
            /** Datetime */
            Datetime: string;
            /** Open */
            Open: number;
            /** High */
            High: number;
            /** Low */
            Low: number;
            /** Close */
            Close: number;
            /** Volume */
            Volume: number;
        };
        /** StockIndicatorsPoint */
        StockIndicatorsPoint: {
            /** Datetime */
            Datetime: string;
            /** Sma 20 */
            SMA_20?: number | null;
            /** Ema 20 */
            EMA_20?: number | null;
            /** Ema 21 */
            EMA_21?: number | null;
            /** Rsi 14 */
            RSI_14?: number | null;
        };
        /** StockMetrics */
        StockMetrics: {
            /** Last Close */
            last_close: number;
            /** Change */
            change: number;
            /** Pct Change */
            pct_change: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Volume */
            volume: number;
            /** Volatility */
            volatility?: number | null;
            /** Sharpe Ratio */
            sharpe_ratio?: number | null;
            /** Risk Free Rate */
            risk_free_rate: number;
        };
        /**
         * TimeframeConfig
         * @description Timeframe mapping for chart controls.
         */
        TimeframeConfig: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Days */
            days: number | null;
            /** Period */
            period: string;
            /** Interval */
            interval: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_stock_metrics_api_stock__ticker__get: {
        parameters: {
            query?: {
                /** @description Time period (e.g., 1d, 5d, 1mo) */
                period?: string;
                /** @description Data interval (e.g., 1m, 5m, 1h) */
                interval?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMetrics"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_stock_history_api_stock__ticker__history_get: {
        parameters: {
            query?: {
                period?: string;
                interval?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockHistoryPoint"][];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_stock_indicators_api_stock__ticker__indicators_get: {
        parameters: {
            query?: {
                period?: string;
                interval?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockIndicatorsPoint"][];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_stock_fundamentals_api_stock__ticker__fundamentals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockFundamentals"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_summary_api_macro_summary_get: {
        parameters: {
            query?: {
                /** @description Number of days of history to return */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroSummaryResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_liquidity_api_macro_liquidity_get: {
        parameters: {
            query?: {
                /** @description Number of days of history to return */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiquidityResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_debt_status_api_macro_debt_status_get: {
        parameters: {
            query?: {
                /** @description Number of days of history to return */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtStatusResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_real_rates_api_macro_real_rates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealRatesResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_cpi_api_macro_cpi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CPIResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_macro_series_api_macro_series_get: {
        parameters: {
            query: {
                /** @description Comma-separated list of FRED series IDs (e.g., 'M2SL,CPIAUCSL') */
                series_ids: string;
                /** @description Number of days of history to return */
                days?: number;
                /** @description Resample lower-frequency data to daily for chart alignment */
                resample?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroSeriesResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_available_overlays_api_macro_overlays_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableOverlaysResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sentiment_api_sentiment__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentimentResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    barbell_comparison_endpoint_api_comparison_barbell_get: {
        parameters: {
            query?: {
                /** @description Time period (e.g. 1y, ytd) */
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResult"][];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_risk_data_api_v1_risk__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_risk_score_api_v1_risk__ticker__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskScoreResponse"];
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_crypto_dominance_api_crypto_dominance_get: {
        parameters: {
            query?: {
                /** @description Number of days of history to return (max 365 for demo key) */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid Request / Bad Input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream Provider Error (FRED/Yahoo/Connectivity) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_app_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfigResponse"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    detailed_health_check_health_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
